#!/bin/bash

BASHRC_FILE="/etc/bash.bashrc"

# Check if the machinectl function is already defined
if ! grep -q "machinectl()" "$BASHRC_FILE"; then
    cat << 'EOF' >> "$BASHRC_FILE"

machinectl() {
    if [ "$1" != "enter" ] || [ -z "$2" ]; then
        command machinectl "$@"
        return
    fi
    local pid=$(command machinectl show "$2" -p Leader --value 2>/dev/null)
    if [ -z "$pid" ] || [ "$pid" = "0" ]; then
        echo "Could not get properties of machine '$2': No machine '$2' known" >&2
        return 1
    fi
    export TERM=$TERM
    sudo nsenter --target "$pid" --mount --net --uts --ipc --pid /bin/bash
}
EOF

fi

# Проверка, что скрипт вызван во время настройки пакета
if [ "$1" = "configure" ]; then
    echo "Настройка службы vlab-servers..."
    
    # Перезагружаем конфигурацию systemd, чтобы она увидела новый файл службы
    systemctl daemon-reload

    # Включаем автозапуск службы при загрузке системы
    systemctl enable vlab-servers.service

    # Перезапускаем или запускаем службу
    systemctl restart vlab-servers.service
fi

exit 0
