#!/bin/bash

BASHRC_FILE="/etc/bash.bashrc"

# Проверяем, что скрипт вызван для удаления или обновления
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
    echo "Остановка службы..."
    systemctl stop vlab-servers.service || true
    
    echo "Отключение автозапуска службы..."
    systemctl disable vlab-servers.service || true
fi

# Если функция присутствует в файле, вырезаем её
if [ -f "$BASHRC_FILE" ] && grep -q "machinectl()" "$BASHRC_FILE"; then
    # Удаляем весь блок от объявления функции до закрывающей фигурной скобки
    sed -i '/machinectl() {/,/}/d' "$BASHRC_FILE"
fi

exit 0
