---
- name: Ветка деплоя среды виртуализации
  when: (vlab_action | default('deploy_vlab')) == 'deploy_vlab'
  environment:
    # Переменные окружения, передаваемые внутрь контекста become_user
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  block:
    - name: Маршрутизация задачи deploy_vlab
      include_tasks: "deploy_vlab.yml"

- name: Ветка остальных задач, выполняемых от имени user
  when: (vlab_action | default('deploy_vlab')) != 'deploy_vlab'
  become_user: "{{ user }}"
  environment:
    # Переменные окружения, передаваемые внутрь контекста become_user
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  block:
    - name: Определение пути к рабочему столу обучаемого
      command: "xdg-user-dir DESKTOP"
      register: xdg_desktop_path
      changed_when: false
      failed_when: false

    - name: Установка дефолтного пути, если xdg-user-dir не вернул результат
      set_fact:
        desktop_path: "{{ xdg_desktop_path.stdout | default('~/Desktop') }}"

    - name: Маршрутизация остальных задач роли vlab
      include_tasks: "{{ vlab_action }}.yml"
